sudo: false

language: python
cache: pip

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
python:
    - '2.7'

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - codecov
